#!/bin/sh
ssh ubuntu@13.82.2.236 <<EOF
    git clone https://github.com/arijitmhptr/demoapp.git
    cd ~/demoapp
    export PATH=/home/arijit/.nvm/versions/node/v14.15.0/bin/npm
    npm install
    npm install -g nodemon pm2
    pm2 start app.js
    exit
EOF